// Generated by gencpp from file beginner_tutorials/StudentInfo.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_STUDENTINFO_H
#define BEGINNER_TUTORIALS_MESSAGE_STUDENTINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct StudentInfo_
{
  typedef StudentInfo_<ContainerAllocator> Type;

  StudentInfo_()
    : name()
    , age(0)
    , gpa(0.0)
    , student_id()  {
    }
  StudentInfo_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , gpa(0.0)
    , student_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int32_t _age_type;
  _age_type age;

   typedef float _gpa_type;
  _gpa_type gpa;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _student_id_type;
  _student_id_type student_id;





  typedef boost::shared_ptr< ::beginner_tutorials::StudentInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::StudentInfo_<ContainerAllocator> const> ConstPtr;

}; // struct StudentInfo_

typedef ::beginner_tutorials::StudentInfo_<std::allocator<void> > StudentInfo;

typedef boost::shared_ptr< ::beginner_tutorials::StudentInfo > StudentInfoPtr;
typedef boost::shared_ptr< ::beginner_tutorials::StudentInfo const> StudentInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::StudentInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::StudentInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::StudentInfo_<ContainerAllocator1> & lhs, const ::beginner_tutorials::StudentInfo_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.gpa == rhs.gpa &&
    lhs.student_id == rhs.student_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::StudentInfo_<ContainerAllocator1> & lhs, const ::beginner_tutorials::StudentInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::StudentInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::StudentInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::StudentInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::StudentInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::StudentInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::StudentInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::StudentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c051919ed71c86bd1ae31babca56f15c";
  }

  static const char* value(const ::beginner_tutorials::StudentInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc051919ed71c86bdULL;
  static const uint64_t static_value2 = 0x1ae31babca56f15cULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::StudentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/StudentInfo";
  }

  static const char* value(const ::beginner_tutorials::StudentInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::StudentInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int32 age\n"
"float32 gpa\n"
"string student_id\n"
;
  }

  static const char* value(const ::beginner_tutorials::StudentInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::StudentInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.gpa);
      stream.next(m.student_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StudentInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::StudentInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::StudentInfo_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age);
    s << indent << "gpa: ";
    Printer<float>::stream(s, indent + "  ", v.gpa);
    s << indent << "student_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.student_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_STUDENTINFO_H
